Improved debug script for Linux/Unix (thanks MustangRocks!)

diff --git a/HTGT-Unix b/HTGT-Unix
--- a/HTGT-Unix
+++ b/HTGT-Unix
@@ -1,6 +1,13 @@
 #!/bin/sh
+java=`which java`
+if test -z "$java"
+then
+	echo "ERROR: Java not found!" 1>&2
+	exit 1
+fi
+
 cd "$(dirname $0)" && \
-java -jar "HTGT.jar" -d 2>> HTGT-Debug.log && \
+"$java" -jar "HTGT.jar" -d 2>> HTGT-Debug.log && \
 exit $? || status=$?
 
 echo; echo "Das Programm wurde mit einem Fehler beendet: $status"
